import { Exhibitor, ExhibitorLead, ExhibitorOperator, ExhibitorDevice, LeadsDashboardData } from '@/types/vello';

export const mockExhibitor: Exhibitor = {
    id: 'exh_1',
    tenantId: 'tenant_1',
    eventId: 'event_1',
    name: 'Vello Tech Solutions',
    cnpj: '12.345.678/0001-90',
    email: 'contato@vellotech.com',
    phone: '(11) 98765-4321',
    logoUrl: 'https://picsum.photos/seed/vello/200/200',
    contactName: 'Ricardo Vello',
    credentialCapacity: 500,
    formId: 'form_1',
    publicToken: 'vello_token_xyz',
    sponsorId: null,
    leadsDeviceLimit: 5,
    status: 'ativo',
    createdAt: new Date('2024-01-01'),
};

export const mockOperators: ExhibitorOperator[] = [
    { id: 'op_1', exhibitorId: 'exh_1', name: 'Ana Silva', pinHash: '****', isActive: true, createdAt: new Date() },
    { id: 'op_2', exhibitorId: 'exh_1', name: 'Bruno Costa', pinHash: '****', isActive: true, createdAt: new Date() },
    { id: 'op_3', exhibitorId: 'exh_1', name: 'Carla Dias', pinHash: '****', isActive: false, createdAt: new Date() },
];

export const mockDevices: ExhibitorDevice[] = [
    { id: 'dev_1', exhibitorId: 'exh_1', deviceId: 'iphone_15_1', deviceName: 'iPhone 15 Pro - Ana', currentOperatorId: 'op_1', currentOperatorName: 'Ana Silva', loggedAt: new Date(), createdAt: new Date() },
    { id: 'dev_2', exhibitorId: 'exh_1', deviceId: 'galaxy_s24_1', deviceName: 'Galaxy S24 - Bruno', currentOperatorId: 'op_2', currentOperatorName: 'Bruno Costa', loggedAt: new Date(), createdAt: new Date() },
];

export const mockLeads: ExhibitorLead[] = [
    {
        id: 'lead_1',
        tenantId: 'tenant_1',
        eventId: 'event_1',
        exhibitorId: 'exh_1',
        credentialId: 'cred_101',
        operatorId: 'op_1',
        operatorName: 'Ana Silva',
        accessCode: 'ABC-123',
        name: 'João Pereira',
        email: 'joao.pereira@gmail.com',
        document: '123.456.789-00',
        phone: '(11) 91234-5678',
        company: 'Tech Corp',
        role: 'CTO',
        note: 'Interessado na API de integração.',
        rating: 'hot',
        syncedAt: new Date(),
        capturedAt: new Date(),
        createdAt: new Date(),
    },
    {
        id: 'lead_2',
        tenantId: 'tenant_1',
        eventId: 'event_1',
        exhibitorId: 'exh_1',
        credentialId: 'cred_102',
        operatorId: 'op_2',
        operatorName: 'Bruno Costa',
        accessCode: 'XYZ-789',
        name: 'Maria Oliveira',
        email: 'maria.o@empresa.com',
        document: '987.654.321-11',
        phone: '(21) 98888-7777',
        company: 'Inova S.A.',
        role: 'Gerente de Marketing',
        note: 'Pediu orçamento para 10 licenças.',
        rating: 'warm',
        syncedAt: new Date(),
        capturedAt: new Date(),
        createdAt: new Date(),
    },
    {
        id: 'lead_3',
        tenantId: 'tenant_1',
        eventId: 'event_1',
        exhibitorId: 'exh_1',
        credentialId: null,
        operatorId: 'op_1',
        operatorName: 'Ana Silva',
        accessCode: null,
        name: 'Carlos Santos',
        email: 'carlos@freelance.com',
        document: null,
        phone: null,
        company: 'Freelance',
        role: 'Developer',
        note: 'Apenas curioso.',
        rating: 'cold',
        syncedAt: new Date(),
        capturedAt: new Date(),
        createdAt: new Date(),
    },
];

export const mockDashboardData: LeadsDashboardData = {
    exhibitor: mockExhibitor,
    eventTitle: 'Vello Summit 2024',
    totalLeads: 124,
    leadsToday: 45,
    activeDevices: 2,
    deviceLimit: 5,
    operators: 3,
    leadsByRating: {
        hot: 42,
        warm: 58,
        cold: 24,
    },
    recentLeads: mockLeads,
    trendData: [
        { time: '09:00', leads: 5 },
        { time: '10:00', leads: 12 },
        { time: '11:00', leads: 25 },
        { time: '12:00', leads: 18 },
        { time: '13:00', leads: 32 },
        { time: '14:00', leads: 45 },
        { time: '15:00', leads: 38 },
        { time: '16:00', leads: 28 },
    ],
    operatorPerformance: [
        { name: 'Ana Silva', leads: 54, color: '#EA580C' },
        { name: 'Bruno Costa', leads: 42, color: '#F97316' },
        { name: 'Carla Dias', leads: 28, color: '#737373' },
    ]
};
